/** Auth and shared API path segments (relative to `environment.apiBaseUrl`). */
export const ApiPaths = {
  authLogin: 'auth/login/',
  authLoginVerifyOtp: 'auth/login/verify-otp/',
  authOtpSend: 'auth/otp/send/',
  authPasswordChange: 'auth/password/change/',
  authPasswordResetRequest: 'auth/password/reset/request/',
  authPasswordResetConfirm: 'auth/password/reset/confirm/',
  authRegister: 'auth/register/',
  authLogout: 'auth/logout/',
  authTokenRefresh: 'auth/token/refresh/',
  authProfile: 'auth/profile/',
  authAvatar: 'auth/avatar/',
  authVerify: 'auth/verify/',
  authSumsubAccessToken: 'auth/kyc/sumsub/access-token/',
  authSumsubWebsdkLink: 'auth/kyc/sumsub/websdk-link/',
  authSumsubReturn: 'auth/kyc/sumsub/return/',
  authGenerateAlias: 'auth/generate-alias/',
  authRegenerateAlias: 'auth/regenerate-alias/',
  authMetadata: 'auth/metadata/',
  authAcceptLegal: 'auth/accept-legal/',
  authEmailVerifySend: 'auth/email/verify/send/',
  authEmailVerify: 'auth/email/verify/',
  legalDocument: (documentType: string) => `legal/${documentType}/`,
  staffOverview: 'staff/overview/',
  staffPlatformSettings: 'staff/platform-settings/',
  staffFees: 'staff/fees/',
  staffFeesSummary: 'staff/fees/summary/',
  staffFeeCategories: 'staff/fees/categories/',
  staffFeeCategory: (id: string) => `staff/fees/categories/${id}/`,
  staffOrganizationFeeSettings: (id: string) => `staff/organizations/${id}/fee-settings/`,
  organizations: 'organizations/',
  organizationsDiscovery: 'organizations/discovery/',
  organizationsMineSummary: 'organizations/mine-summary/',
  organizationTypes: 'organizations/types/',
  organizationCountries: 'organizations/countries/',
  organizationCities: 'organizations/cities/',
  organization: (id: string) => `organizations/${id}/`,
  organizationAddresses: (orgId: string) => `organizations/${orgId}/addresses/`,
  organizationAddress: (orgId: string, addressId: string) =>
    `organizations/${orgId}/addresses/${addressId}/`,
  organizationTeam: (id: string) => `organizations/${id}/team/`,
  organizationTeamInvite: (id: string) => `organizations/${id}/team/invite/`,
  organizationTeamMember: (organizationId: string, membershipId: string) =>
    `organizations/${organizationId}/team/${membershipId}/`,
  organizationAnalytics: (id: string) => `organizations/${id}/analytics/`,
  organizationSubmitVerification: (id: string) => `organizations/${id}/submit-verification/`,
  organizationServices: (orgId: string) => `organizations/${orgId}/services/`,
  organizationService: (orgId: string, serviceId: string) =>
    `organizations/${orgId}/services/${serviceId}/`,
  organizationServiceMedia: (orgId: string, serviceId: string) =>
    `organizations/${orgId}/services/${serviceId}/media/`,
  services: 'services/',
  serviceCategories: 'services/categories/',
  serviceSubcategories: 'services/subcategories/',
  serviceFeatures: 'services/features/',
  notifications: 'notifications/',
  notificationMarkRead: (id: string) => `notifications/${id}/mark-read/`,
  notificationsMarkAllRead: 'notifications/mark-all-read/',
  notificationsUnreadCount: 'notifications/unread-count/',
  messagingInvites: 'messaging/invites/',
  messagingInvitesIncoming: 'messaging/invites/incoming/',
  messagingInviteAccept: (id: string) => `messaging/invites/${id}/accept/`,
  messagingInviteDecline: (id: string) => `messaging/invites/${id}/decline/`,
  messagingConversations: 'messaging/conversations/',
  messagingConversation: (id: string) => `messaging/conversations/${id}/`,
  messagingBookingThread: 'messaging/conversations/booking/',
  messagingSupportThread: 'messaging/conversations/support/',
  messagingPlatformSupportThread: 'messaging/conversations/platform-support/',
  messagingMessages: (id: string) => `messaging/conversations/${id}/messages/`,
  messagingBlock: (id: string) => `messaging/conversations/${id}/block/`,
  messagingUnblock: (id: string) => `messaging/conversations/${id}/unblock/`,
  messagingRead: (id: string) => `messaging/conversations/${id}/read/`,
  bookings: 'bookings/',
  bookingCancel: (id: string) => `bookings/${id}/cancel/`,
  serviceOpenSlots: (serviceId: string) => `services/${serviceId}/open-slots/`,
  bookingConfirm: (id: string) => `bookings/${id}/confirm/`,
  bookingReject: (id: string) => `bookings/${id}/reject/`,
  bookingComplete: (id: string) => `bookings/${id}/complete/`,
  bookingReschedule: (id: string) => `bookings/${id}/reschedule/`,
  bookingRescheduleAccept: (id: string) => `bookings/${id}/reschedule/accept/`,
  bookingRescheduleDecline: (id: string) => `bookings/${id}/reschedule/decline/`,
  bookingPaymentLink: (bookingId: string) => `payments/bookings/${bookingId}/payment-link/`,
  paymentWallet: 'payments/wallet/',
  paymentWalletTopUp: 'payments/wallet/top-up/',
  paymentTransaction: (clientReference: string) => `payments/transactions/${clientReference}/`,
  staffUsers: 'staff/users/',
  staffUser: (id: string) => `staff/users/${id}/`,
  staffUserApprove: (id: string) => `staff/users/${id}/approve/`,
  staffUserReject: (id: string) => `staff/users/${id}/reject/`,
  staffUserWallet: (id: string) => `staff/users/${id}/wallet/`,
  staffUserWalletCredit: (id: string) => `staff/users/${id}/wallet/credit/`,
  staffUserWalletDebit: (id: string) => `staff/users/${id}/wallet/debit/`,
  staffOrgRevenueDebit: (id: string) => `staff/organizations/${id}/revenue/debit/`,
  staffFxRates: 'staff/fx-rates/',
  staffSettlements: 'staff/settlements/',
  staffSettlementComplete: (id: string) => `staff/settlements/${id}/complete/`,
  staffSettlementReject: (id: string) => `staff/settlements/${id}/reject/`,
  staffOrganizations: 'staff/organizations/',
  staffOrganization: (id: string) => `staff/organizations/${id}/`,
  staffOrganizationApprove: (id: string) => `staff/organizations/${id}/approve/`,
  staffOrganizationReject: (id: string) => `staff/organizations/${id}/reject/`,
  staffOrganizationSuspend: (id: string) => `staff/organizations/${id}/suspend/`,
  staffOrganizationUnsuspend: (id: string) => `staff/organizations/${id}/unsuspend/`,
  staffTaxonomyCategories: 'staff/taxonomy/categories/',
  staffTaxonomyCategory: (id: string) => `staff/taxonomy/categories/${id}/`,
  staffTaxonomySubcategories: 'staff/taxonomy/subcategories/',
  staffTaxonomySubcategory: (id: string) => `staff/taxonomy/subcategories/${id}/`,
  staffTaxonomyFeatures: 'staff/taxonomy/features/',
  staffTaxonomyFeature: (id: string) => `staff/taxonomy/features/${id}/`,
  staffPayments: 'staff/payments/',
} as const;

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
