# Generated by Django 4.2.29 on 2026-04-04 17:09

from django.db import migrations, models


def forwards_user_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    role_map = {
        'ADMIN': 'A',
        'BUSINESS_OWNER': 'O',
        'BUSINESS_STAFF': 'S',
        'CLIENT': 'C',
    }
    ver_map = {
        'PENDING': 'P',
        'VERIFIED': 'V',
        'REJECTED': 'R',
    }
    for u in User.objects.all().iterator():
        changed = []
        if u.role and len(str(u.role)) > 1:
            u.role = role_map.get(str(u.role), u.role)
            changed.append('role')
        if u.verification_status and len(str(u.verification_status)) > 1:
            u.verification_status = ver_map.get(str(u.verification_status), u.verification_status)
            changed.append('verification_status')
        if changed:
            u.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.RunPython(forwards_user_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('A', 'Admin'),
                    ('O', 'Business Owner'),
                    ('S', 'Business Staff'),
                    ('C', 'Client'),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(
                choices=[
                    ('P', 'Pending Verification'),
                    ('V', 'Verified'),
                    ('R', 'Rejected'),
                ],
                default='P',
                max_length=1,
            ),
        ),
    ]
