# Generated by Django 4.2.29 on 2026-04-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role_alter_user_verification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("A", "Admin"), ("O", "Business Owner"), ("S", "Business Staff"), ("C", "Client")],
                default="C",
                max_length=1,
            ),
        ),
    ]
