# Generated by Django 4.2.29 on 2026-07-18 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_date_of_birth_user_sex_user_show_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocumentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(choices=[("T", "Terms of Service"), ("P", "Privacy Policy")], max_length=1),
                ),
                ("version", models.CharField(max_length=32)),
                ("effective_at", models.DateTimeField()),
                ("is_current", models.BooleanField(default=False)),
                ("body_en", models.TextField()),
                ("body_fr", models.TextField()),
                ("summary_en", models.CharField(blank=True, max_length=500)),
                ("summary_fr", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "legal_document_versions",
                "ordering": ["-effective_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLegalAcceptance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("S", "Signup"), ("R", "Re-accept"), ("G", "Google signup")], default="S", max_length=1
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="users.legaldocumentversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_legal_acceptances",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="legaldocumentversion",
            index=models.Index(fields=["document_type", "is_current"], name="legal_docum_documen_1e335d_idx"),
        ),
        migrations.AddConstraint(
            model_name="legaldocumentversion",
            constraint=models.UniqueConstraint(
                fields=("document_type", "version"), name="unique_legal_doc_type_version"
            ),
        ),
        migrations.AddIndex(
            model_name="userlegalacceptance",
            index=models.Index(fields=["user", "document"], name="user_legal__user_id_15c684_idx"),
        ),
        migrations.AddIndex(
            model_name="userlegalacceptance",
            index=models.Index(fields=["accepted_at"], name="user_legal__accepte_2577b2_idx"),
        ),
    ]
