# Generated by Django 4.2.29 on 2026-07-25 13:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


def copy_legal_ip_ua_to_audit(apps, schema_editor):
    UserLegalAcceptance = apps.get_model('users', 'UserLegalAcceptance')
    AuditEvent = apps.get_model('core', 'AuditEvent')
    for row in UserLegalAcceptance.objects.all().iterator():
        if not row.ip_address and not row.user_agent:
            continue
        event = AuditEvent.objects.create(
            id=uuid.uuid4(),
            user_id=row.user_id,
            action='legal.accept',
            ip_address=row.ip_address,
            user_agent=row.user_agent or '',
        )
        UserLegalAcceptance.objects.filter(pk=row.pk).update(audit_event_id=event.id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_audit_event_mixin'),
        ('users', '0009_seed_privacy_turnstile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlegalacceptance',
            name='audit_event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.auditevent',
            ),
        ),
        migrations.RunPython(copy_legal_ip_ua_to_audit, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userlegalacceptance',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userlegalacceptance',
            name='user_agent',
        ),
    ]
