# Generated by Django 4.2.29 on 2026-07-26 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_sumsub_applicant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKycSumsubEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("applicant_id", models.CharField(blank=True, default="", max_length=64)),
                ("inspection_id", models.CharField(blank=True, default="", max_length=64)),
                ("sandbox", models.BooleanField(default=False)),
                ("redirect_status", models.CharField(blank=True, default="", max_length=64)),
                ("review_answer", models.CharField(blank=True, default="", max_length=32)),
                ("applicant_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_sumsub_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_kyc_sumsub_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
