# Generated by Django 4.2.29 on 2026-07-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_kyc_sumsub_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="inscription_fee_paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When the one-time verification/inscription fee was collected.", null=True
            ),
        ),
    ]
