# Generated by Django 4.2.29 on 2026-03-29 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('business_license_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('business_license_document', models.FileField(blank=True, null=True, upload_to='verification_documents/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='verification_documents/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_bookings', models.BooleanField(default=True)),
                ('requires_prepayment', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('minimum_booking_hours_notice', models.PositiveIntegerField(default=2)),
                ('maximum_booking_days_ahead', models.PositiveIntegerField(default=30)),
                ('cancellation_hours_notice', models.PositiveIntegerField(default=24)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.15, max_digits=5)),
                ('payout_delay_days', models.PositiveIntegerField(default=7)),
            ],
            options={
                'db_table': 'organization_settings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationTypeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization_types',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTypeSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_subcategories', to='organizations.organizationtypemodel')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_types', to='services.servicesubcategory')),
            ],
            options={
                'db_table': 'organization_type_subcategories',
                'ordering': ['organization_type', 'sub_category'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationtypemodel',
            index=models.Index(fields=['name'], name='organizatio_name_ca7f62_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtypemodel',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_d393e6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtypemodel',
            index=models.Index(fields=['display_name'], name='organizatio_display_cfe458_idx'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.organizationtypemodel'),
        ),
        migrations.AddIndex(
            model_name='organizationtypesubcategory',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_a8d48e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtypesubcategory',
            index=models.Index(fields=['sub_category'], name='organizatio_sub_cat_a9e98e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtypesubcategory',
            index=models.Index(fields=['is_default'], name='organizatio_is_defa_e6de43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationtypesubcategory',
            unique_together={('organization_type', 'sub_category')},
        ),
        migrations.AddIndex(
            model_name='organizationsettings',
            index=models.Index(fields=['organization'], name='organizatio_organiz_423e61_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['type'], name='organizatio_type_id_c6b479_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['verification_status'], name='organizatio_verific_21fa85_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email'], name='organizatio_email_56e6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['deleted_at'], name='organizatio_deleted_0c15ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_organization_email'),
        ),
    ]
