# Generated by Django 4.2.29 on 2026-04-04 17:09

from django.db import migrations, models


def forwards_org_codes(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMembership = apps.get_model('organizations', 'OrganizationMembership')
    ver_map = {
        'PENDING': 'P',
        'VERIFIED': 'V',
        'REJECTED': 'R',
        'SUSPENDED': 'S',
    }
    role_map = {
        'OWNER': 'O',
        'ADMIN': 'A',
        'MANAGER': 'M',
        'STAFF': 'T',
        'CASHIER': 'C',
        'DELIVERY': 'D',
    }
    for o in Organization.objects.all().iterator():
        if o.verification_status and len(str(o.verification_status)) > 1:
            o.verification_status = ver_map.get(str(o.verification_status), o.verification_status)
            o.save(update_fields=['verification_status'])
    for m in OrganizationMembership.objects.all().iterator():
        if m.role and len(str(m.role)) > 1:
            m.role = role_map.get(str(m.role), m.role)
            m.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_membership'),
    ]

    operations = [
        migrations.RunPython(forwards_org_codes, migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_user_id_db5190_idx',
            old_name='organization_membe_user_id_6f8b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_organiz_f62334_idx',
            old_name='organization_membe_organiz_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_role_e3a08a_idx',
            old_name='organization_membe_role_3d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(
                choices=[
                    ('P', 'Pending Verification'),
                    ('V', 'Verified'),
                    ('R', 'Rejected'),
                    ('S', 'Suspended'),
                ],
                default='P',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(
                choices=[
                    ('O', 'Owner'),
                    ('A', 'Admin'),
                    ('M', 'Manager'),
                    ('T', 'Staff'),
                    ('C', 'Cashier'),
                    ('D', 'Delivery'),
                ],
                default='T',
                max_length=1,
            ),
        ),
    ]
