# Generated by Django 4.2.29 on 2026-04-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_country_currency_link_and_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationaddress",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="organizations.country",
            ),
        ),
    ]
