# Generated by Django 4.2.29 on 2026-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organizationaddress_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="require_client_name",
            field=models.BooleanField(default=True),
        ),
    ]
