# Generated by Django 4.2.29 on 2026-07-18 20:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0010_organization_require_client_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTeamInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("O", "Owner"),
                            ("A", "Admin"),
                            ("M", "Manager"),
                            ("T", "Staff"),
                            ("C", "Cashier"),
                            ("D", "Delivery"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_team_invites_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_invites",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_team_invites",
                "indexes": [
                    models.Index(fields=["organization"], name="organizatio_organiz_9325d5_idx"),
                    models.Index(fields=["email"], name="organizatio_email_014c1b_idx"),
                    models.Index(fields=["token"], name="organizatio_token_d7088c_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="organizationteaminvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accepted_at__isnull", True)),
                fields=("organization", "email"),
                name="unique_pending_organization_team_invite",
            ),
        ),
    ]
