# Generated by Django 4.2.29 on 2026-07-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_organizationteaminvite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationsettings",
            name="commission_rate",
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="platform_fee_payer",
            field=models.CharField(choices=[("C", "Client"), ("B", "Business")], default="C", max_length=1),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="platform_fee_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional company-specific platform fee percent; null inherits category/global.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
