# Generated by Django 4.2.29 on 2026-07-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_platform_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="accepted_location_types",
            field=models.JSONField(
                blank=True, default=list, help_text="Venue types accepted for bookings (O/H/V/B). Empty means all four."
            ),
        ),
    ]
