# Generated by Django 4.2.29 on 2026-07-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_cities_country_and_city_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="annual_fee_paid_through",
            field=models.DateField(
                blank=True,
                help_text="Inclusive end date of the paid annual business subscription period.",
                null=True,
            ),
        ),
    ]
