# Generated by Django 4.2.29 on 2026-07-26 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ("organizations", "0015_fees_settlement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationaddress",
            name="cities_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_set", to=settings.CITIES_CITY_MODEL
            ),
        ),
    ]
