# Generated by Django 4.2.29 on 2026-03-29 19:04

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_bookings_per_day', models.PositiveIntegerField(default=10, help_text='Maximum bookings allowed per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_bookings_per_time_slot', models.PositiveIntegerField(default=1, help_text='Maximum bookings per time slot', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('booking_advance_days', models.PositiveIntegerField(default=30, help_text='Days in advance bookings can be made', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('minimum_booking_hours', models.PositiveIntegerField(default=2, help_text='Minimum hours before booking time', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('cancellation_hours', models.PositiveIntegerField(default=24, help_text='Hours before booking for cancellation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('available_start_time', models.TimeField(blank=True, help_text='Earliest time this can be booked', null=True)),
                ('available_end_time', models.TimeField(blank=True, help_text='Latest time this can be booked', null=True)),
                ('available_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10), blank=True, default=list, help_text='Days of the week when available', size=None)),
                ('seasonal_start_date', models.DateField(blank=True, help_text='Start date for seasonal availability', null=True)),
                ('seasonal_end_date', models.DateField(blank=True, help_text='End date for seasonal availability', null=True)),
                ('availability_notes', models.TextField(blank=True, help_text='Notes about availability or special conditions')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('requires_verification', models.BooleanField(default=True)),
                ('availability_type', models.CharField(choices=[('ALWAYS', 'Always Available'), ('SCHEDULED', 'Scheduled Times'), ('ON_DEMAND', 'On Demand'), ('APPOINTMENT', 'Appointment Only')], default='APPOINTMENT', max_length=15)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'service_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(choices=[('AMENITY', 'Amenity'), ('REQUIREMENT', 'Requirement'), ('SAFETY', 'Safety Feature')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'service_features',
                'ordering': ['feature_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVariantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('duration_type', models.CharField(choices=[('FIXED', 'Fixed Duration'), ('FLEXIBLE', 'Flexible Duration')], default='FIXED', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service')),
            ],
            options={
                'db_table': 'service_variants',
                'ordering': ['is_popular', 'duration_minutes'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_options', models.JSONField(blank=True, default=list, help_text='List of available durations in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='services.servicecategory')),
            ],
            options={
                'db_table': 'service_sub_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='service_media/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.service')),
            ],
            options={
                'db_table': 'service_media',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeatureMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='services.servicefeature')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_mappings', to='services.service')),
            ],
            options={
                'db_table': 'service_feature_mappings',
            },
        ),
        migrations.AddIndex(
            model_name='servicefeature',
            index=models.Index(fields=['feature_type'], name='service_fea_feature_a41c83_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeature',
            index=models.Index(fields=['name'], name='service_fea_name_9c9e79_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['name'], name='service_cat_name_263675_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active'], name='service_cat_is_acti_c27f89_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['sort_order'], name='service_cat_sort_or_b8eb30_idx'),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicesubcategory'),
        ),
        migrations.AddIndex(
            model_name='servicevariantmodel',
            index=models.Index(fields=['service'], name='service_var_service_19c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevariantmodel',
            index=models.Index(fields=['duration_minutes'], name='service_var_duratio_530d10_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevariantmodel',
            index=models.Index(fields=['price'], name='service_var_price_ecd281_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevariantmodel',
            index=models.Index(fields=['is_popular'], name='service_var_is_popu_cd4c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevariantmodel',
            index=models.Index(fields=['is_active'], name='service_var_is_acti_fa06c7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['category'], name='service_sub_categor_0dcc20_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['name'], name='service_sub_name_b18d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['is_active'], name='service_sub_is_acti_548093_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['sort_order'], name='service_sub_sort_or_11e99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicesubcategory',
            unique_together={('name', 'category')},
        ),
        migrations.AddIndex(
            model_name='servicemedia',
            index=models.Index(fields=['service'], name='service_med_service_04c5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemedia',
            index=models.Index(fields=['media_type'], name='service_med_media_t_3dedf4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemedia',
            index=models.Index(fields=['is_primary'], name='service_med_is_prim_f77f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemedia',
            index=models.Index(fields=['sort_order'], name='service_med_sort_or_4439e7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeaturemapping',
            index=models.Index(fields=['service'], name='service_fea_service_2a1148_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeaturemapping',
            index=models.Index(fields=['feature'], name='service_fea_feature_eb840c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeaturemapping',
            index=models.Index(fields=['is_required'], name='service_fea_is_requ_4e26f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicefeaturemapping',
            unique_together={('service', 'feature')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['sub_category'], name='services_sub_cat_dfad7b_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='services_name_a79f61_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_is_acti_b1f5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['featured'], name='services_feature_8217a7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price_min'], name='services_price_m_ad7e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['availability_type'], name='services_availab_6dcde8_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['deleted_at'], name='services_deleted_8e32dd_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['available_days'], name='services_availab_a8ab2f_idx'),
        ),
    ]
