# Generated by Django 4.2.29 on 2026-03-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_verified_by'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization'], name='services_organiz_12bd44_idx'),
        ),
    ]
