# Generated by Django 4.2.29 on 2026-04-04 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


def forwards_service_codes(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceFeature = apps.get_model('services', 'ServiceFeature')
    ServiceMedia = apps.get_model('services', 'ServiceMedia')
    ServiceVariantModel = apps.get_model('services', 'ServiceVariantModel')

    avail = {
        'ALWAYS': 'A',
        'SCHEDULED': 'S',
        'ON_DEMAND': 'O',
        'APPOINTMENT': 'P',
    }
    feature = {
        'AMENITY': 'A',
        'REQUIREMENT': 'R',
        'SAFETY': 'S',
    }
    media = {
        'IMAGE': 'I',
        'VIDEO': 'V',
        'DOCUMENT': 'D',
    }
    variant = {
        'FIXED': 'F',
        'FLEXIBLE': 'X',
    }
    day = {
        'MONDAY': 'M',
        'TUESDAY': 'T',
        'WEDNESDAY': 'W',
        'THURSDAY': 'H',
        'FRIDAY': 'F',
        'SATURDAY': 'S',
        'SUNDAY': 'U',
    }

    for s in Service.objects.all().iterator():
        changed = []
        if s.availability_type and len(str(s.availability_type)) > 1:
            s.availability_type = avail.get(str(s.availability_type), s.availability_type)
            changed.append('availability_type')
        if s.available_days:
            new_days = []
            for d in s.available_days:
                if isinstance(d, str) and len(d) > 1:
                    new_days.append(day.get(d, d))
                else:
                    new_days.append(d)
            if new_days != s.available_days:
                s.available_days = new_days
                changed.append('available_days')
        if changed:
            s.save(update_fields=changed)

    for f in ServiceFeature.objects.all().iterator():
        if f.feature_type and len(str(f.feature_type)) > 1:
            f.feature_type = feature.get(str(f.feature_type), f.feature_type)
            f.save(update_fields=['feature_type'])

    for m in ServiceMedia.objects.all().iterator():
        if m.media_type and len(str(m.media_type)) > 1:
            m.media_type = media.get(str(m.media_type), m.media_type)
            m.save(update_fields=['media_type'])

    for v in ServiceVariantModel.objects.all().iterator():
        if v.duration_type and len(str(v.duration_type)) > 1:
            v.duration_type = variant.get(str(v.duration_type), v.duration_type)
            v.save(update_fields=['duration_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_organization_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_service_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='availability_type',
            field=models.CharField(
                choices=[
                    ('A', 'Always Available'),
                    ('S', 'Scheduled Times'),
                    ('O', 'On Demand'),
                    ('P', 'Appointment Only'),
                ],
                default='P',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='available_days',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('M', 'Monday'),
                        ('T', 'Tuesday'),
                        ('W', 'Wednesday'),
                        ('H', 'Thursday'),
                        ('F', 'Friday'),
                        ('S', 'Saturday'),
                        ('U', 'Sunday'),
                    ],
                    max_length=1,
                ),
                blank=True,
                default=list,
                help_text='Days of the week when available',
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_type',
            field=models.CharField(
                choices=[('A', 'Amenity'), ('R', 'Requirement'), ('S', 'Safety Feature')],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='media_type',
            field=models.CharField(
                choices=[('I', 'Image'), ('V', 'Video'), ('D', 'Document')],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='servicevariantmodel',
            name='duration_type',
            field=models.CharField(
                choices=[('F', 'Fixed Duration'), ('X', 'Flexible Duration')],
                default='F',
                max_length=1,
            ),
        ),
    ]
