# Generated by Django 4.2.29 on 2026-04-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_availability_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Heroicon name (kebab-case) matching the Flutter heroicons package, e.g. sparkles, heart, user.",
                max_length=50,
            ),
        ),
    ]
