# Generated by Django 4.2.29 on 2026-04-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_organizationaddress_country"),
        ("services", "0005_remove_service_currency_service_accepted_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="organizations.country",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="country_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy free-text country line; prefer country FK when set.",
                max_length=100,
            ),
        ),
    ]
