# Generated by Django 4.2.29 on 2026-07-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_service_country_alter_service_country_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="accepted_location_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Venue types for this service (O/H/V/B). Empty inherits organization defaults.",
            ),
        ),
    ]
