# Generated by Django 4.2.29 on 2026-04-15 00:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finances", "0001_initial"),
        ("bookings", "0003_remove_booking_currency_booking_accepted_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0009_organizationaddress_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("M", "Mobile money"), ("C", "Card"), ("B", "Bank"), ("W", "Wallet"), ("O", "Other")],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "supported_countries",
                    models.ManyToManyField(blank=True, related_name="payment_providers", to="organizations.country"),
                ),
                (
                    "supported_currencies",
                    models.ManyToManyField(blank=True, related_name="payment_providers", to="finances.currency"),
                ),
            ],
            options={
                "db_table": "payment_providers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("A", "Authorization"), ("P", "Payment"), ("R", "Refund"), ("V", "Partial refund")],
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "Pending"),
                            ("G", "Processing"),
                            ("S", "Succeeded"),
                            ("F", "Failed"),
                            ("X", "Cancelled"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=128)),
                ("client_reference", models.CharField(blank=True, max_length=128)),
                ("provider_response_code", models.CharField(blank=True, max_length=64)),
                ("provider_response_body", models.JSONField(blank=True, null=True)),
                ("provider_request_payload", models.JSONField(blank=True, null=True)),
                ("webhook_received_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
                ("webhook_signature_valid", models.BooleanField(blank=True, null=True)),
                ("payer_account_masked", models.CharField(blank=True, max_length=64)),
                ("payee_account_masked", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="finances.currency",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user for refunds/captures initiated by org.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="payments.paymentprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer (payer) when applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions_as_payer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["booking"], name="payment_tra_booking_0a0eb8_idx"),
                    models.Index(fields=["payment_provider"], name="payment_tra_payment_cf15ed_idx"),
                    models.Index(fields=["status"], name="payment_tra_status_137fde_idx"),
                    models.Index(fields=["kind"], name="payment_tra_kind_62214c_idx"),
                    models.Index(fields=["created_at"], name="payment_tra_created_e43546_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("payment_provider", "idempotency_key"),
                name="unique_provider_idempotency_when_set",
            ),
        ),
    ]
