# Generated by Django 4.2.29 on 2026-07-18 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_cancellation_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finances", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundWallet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_wallets",
                        to="finances.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refund_wallets",
                "ordering": ["currency__code"],
            },
        ),
        migrations.CreateModel(
            name="RefundWalletLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(choices=[("C", "Cancellation credit"), ("A", "Applied to booking")], max_length=1),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Absolute amount; sign is implied by kind (credit vs debit).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=128)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_wallet_ledger",
                        to="bookings.booking",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="payments.refundwallet",
                    ),
                ),
            ],
            options={
                "db_table": "refund_wallet_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="refundwalletledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("idempotency_key",),
                name="unique_refund_wallet_ledger_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="refundwallet",
            constraint=models.UniqueConstraint(fields=("user", "currency"), name="unique_refund_wallet_user_currency"),
        ),
    ]
