# Generated by Django 4.2.29 on 2026-07-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_platform_fee_choices"),
        ("payments", "0002_refund_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="purpose",
            field=models.CharField(
                choices=[("B", "Booking payment"), ("W", "Escrow top-up")], db_index=True, default="B", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_transactions",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="refundwalletledger",
            name="kind",
            field=models.CharField(
                choices=[("C", "Cancellation credit"), ("A", "Applied to booking"), ("T", "Escrow top-up")],
                max_length=1,
            ),
        ),
    ]
