# Generated by Django 4.2.29 on 2026-07-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_audit_event_mixin"),
        ("payments", "0003_wallet_topup_and_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="audit_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.auditevent",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="purpose",
            field=models.CharField(
                choices=[("B", "Booking payment"), ("W", "Store credit top-up")],
                db_index=True,
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="refundwalletledger",
            name="kind",
            field=models.CharField(
                choices=[("C", "Cancellation credit"), ("A", "Applied to booking"), ("T", "Store credit top-up")],
                max_length=1,
            ),
        ),
    ]
