# Generated by Django 4.2.29 on 2026-08-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_connector_method"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="payment_met_code_b70caa_idx",
            old_name="payment_met_code_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="payment_met_method__c0df5d_idx",
            old_name="payment_met_type_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="payment_met_is_acti_395fa6_idx",
            old_name="payment_met_active_idx",
        ),
    ]
