# Generated by Django 4.2.29 on 2026-08-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_rename_payment_met_code_idx_payment_met_code_b70caa_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "Pending"),
                    ("G", "Processing"),
                    ("S", "Succeeded"),
                    ("F", "Failed"),
                    ("X", "Cancelled"),
                    ("U", "Refunded"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
