# Generated by Django 4.2.29 on 2026-04-05 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=3, unique=True)),
                ("symbol", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=128)),
                ("numeric_code", models.CharField(max_length=3)),
                (
                    "minor_units",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "db_table": "currencies",
                "ordering": ["code"],
            },
        ),
    ]
