# Generated by Django 4.2.29 on 2026-07-18 23:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_platform_fees"),
        ("services", "0006_alter_service_country_alter_service_country_text"),
        ("bookings", "0006_platform_fees"),
        ("payments", "0002_refund_wallet"),
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform_fee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Global platform fee percent (default 1.00 = 1%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "platform settings",
                "db_table": "platform_settings",
            },
        ),
        migrations.CreateModel(
            name="PlatformFeeEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("payer", models.CharField(choices=[("C", "Client"), ("B", "Business")], max_length=1)),
                (
                    "source",
                    models.CharField(choices=[("G", "Global"), ("C", "Category"), ("O", "Organization")], max_length=1),
                ),
                ("status", models.CharField(choices=[("A", "Accrued"), ("R", "Reversed")], default="A", max_length=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_fee_entries",
                        to="bookings.booking",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_fee_entries",
                        to="services.servicecategory",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_fee_entries",
                        to="finances.currency",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_fee_entries",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_fee_entries",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "platform_fee_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization"], name="platform_fe_organiz_82efc9_idx"),
                    models.Index(fields=["booking"], name="platform_fe_booking_c13d1c_idx"),
                    models.Index(fields=["status"], name="platform_fe_status_19e346_idx"),
                    models.Index(fields=["created_at"], name="platform_fe_created_28c9fa_idx"),
                    models.Index(fields=["payer"], name="platform_fe_payer_3454d4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryPlatformFee",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Platform fee percent for this category.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_fee",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "category_platform_fees",
                "indexes": [models.Index(fields=["category"], name="category_pl_categor_169268_idx")],
            },
        ),
    ]
