# Generated by Django 4.2.29 on 2026-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_seed_platform_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsettings",
            name="id",
            field=models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
