# Generated by Django 4.2.29 on 2026-07-26 22:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_fees_settlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0005_manual_wallet_ledger"),
        ("organizations", "0015_fees_settlement"),
        ("finances", "0004_alter_platformsettings_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementAccount",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "method",
                    models.CharField(
                        choices=[("B", "Bank / IBAN"), ("M", "Mobile money"), ("I", "Interac email")], max_length=1
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=128)),
                ("is_default", models.BooleanField(default=False)),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                ("iban", models.CharField(blank=True, max_length=64)),
                ("bic_swift", models.CharField(blank=True, max_length=32)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("interac_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_bank_accounts",
                        to="organizations.country",
                    ),
                ),
                (
                    "mobile_money_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_momo_accounts",
                        to="organizations.country",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_accounts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "settlement_accounts",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="business_annual_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Annual business subscription fee in USD (converted via FX).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="settlement_minimum_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Minimum settlement amount floor in USD (converted via FX).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="user_inscription_fee_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="One-time user verification fee in USD (converted via FX).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="UserPlatformCharge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("I", "Verification / inscription fee")], max_length=1)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_platform_charges",
                        to="bookings.booking",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_platform_charges",
                        to="finances.currency",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_platform_charges",
                        to="payments.paymenttransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_platform_charges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SettlementSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("W", "Weekly"), ("B", "Biweekly"), ("M", "Monthly"), ("N", "Manual only")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_settings",
                        to="finances.currency",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "settlement_settings",
            },
        ),
        migrations.CreateModel(
            name="SettlementRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Requested"), ("P", "Processing"), ("C", "Completed"), ("X", "Rejected")],
                        default="R",
                        max_length=1,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("B", "Bank / IBAN"), ("M", "Mobile money"), ("I", "Interac email")], max_length=1
                    ),
                ),
                ("destination_snapshot", models.JSONField(blank=True, default=dict)),
                ("staff_note", models.TextField(blank=True)),
                (
                    "confirmation_image",
                    models.ImageField(
                        blank=True,
                        help_text="Staff-only proof of payout; never exposed to businesses.",
                        null=True,
                        upload_to="settlement_confirmations/",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_requests",
                        to="finances.currency",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_requests_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settlement_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="finances.settlementaccount",
                    ),
                ),
            ],
            options={
                "db_table": "settlement_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationRevenueWallet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("balance", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_revenue_wallets",
                        to="finances.currency",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_wallets",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_revenue_wallets",
                "ordering": ["currency__code"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationRevenueLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("B", "Booking credit"),
                            ("P", "Platform fee"),
                            ("A", "Annual subscription"),
                            ("S", "Settlement"),
                            ("T", "Staff adjustment"),
                            ("M", "Manual settlement"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Signed amount: positive credit, negative debit.", max_digits=14
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(blank=True, max_length=512)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_revenue_ledger",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_revenue_ledger_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settlement_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finances.settlementrequest",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="finances.organizationrevenuewallet",
                    ),
                ),
            ],
            options={
                "db_table": "organization_revenue_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyFxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Multiply USD amount by this rate to get to_currency.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
                    ),
                ),
                ("effective_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fx_rates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_rates_from",
                        to="finances.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="fx_rates_to", to="finances.currency"
                    ),
                ),
            ],
            options={
                "db_table": "currency_fx_rates",
                "ordering": ["-effective_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userplatformcharge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "I")), fields=("user", "kind"), name="unique_user_inscription_charge"
            ),
        ),
        migrations.AddIndex(
            model_name="settlementrequest",
            index=models.Index(fields=["organization"], name="settlement__organiz_f25084_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementrequest",
            index=models.Index(fields=["status"], name="settlement__status_ccb857_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementrequest",
            index=models.Index(fields=["created_at"], name="settlement__created_3a3672_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementaccount",
            index=models.Index(fields=["organization"], name="settlement__organiz_c21d67_idx"),
        ),
        migrations.AddIndex(
            model_name="settlementaccount",
            index=models.Index(fields=["method"], name="settlement__method_8ccd8b_idx"),
        ),
        migrations.AddConstraint(
            model_name="organizationrevenuewallet",
            constraint=models.UniqueConstraint(
                fields=("organization", "currency"), name="unique_org_revenue_wallet_currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrevenueledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("idempotency_key",),
                name="unique_org_revenue_ledger_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="currencyfxrate",
            index=models.Index(
                fields=["from_currency", "to_currency", "-effective_at"], name="currency_fx_from_cu_0162af_idx"
            ),
        ),
    ]
