# Generated by Django 4.2.29 on 2026-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0007_settlement_drop_legacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settlementaccount",
            name="account_name",
            field=models.CharField(blank=True, help_text="Account holder / destination name.", max_length=255),
        ),
    ]
