# Generated by Django 4.2.29 on 2026-08-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0008_alter_settlementaccount_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationrevenueledger",
            name="kind",
            field=models.CharField(
                choices=[
                    ("B", "Booking credit"),
                    ("P", "Platform fee"),
                    ("A", "Annual subscription"),
                    ("S", "Settlement"),
                    ("T", "Staff adjustment"),
                    ("M", "Manual settlement"),
                    ("C", "Cancellation debit"),
                    ("L", "Cancellation penalty"),
                ],
                max_length=1,
            ),
        ),
    ]
