/** Maps API Heroicon kebab-case names to Material Symbols ligatures. */
const HEROICON_TO_MATERIAL: Record<string, string> = {
  sparkles: 'auto_awesome',
  heart: 'favorite',
  'heart-solid': 'favorite',
  user: 'person',
  users: 'group',
  home: 'home',
  star: 'star',
  'star-solid': 'star',
  spa: 'spa',
  fire: 'local_fire_department',
  bolt: 'bolt',
  sun: 'wb_sunny',
  moon: 'dark_mode',
  leaf: 'eco',
  'beaker': 'science',
  cake: 'cake',
  camera: 'photo_camera',
  'chat-bubble-left-right': 'chat',
  'calendar-days': 'calendar_month',
  'map-pin': 'location_on',
  globe: 'public',
  gift: 'card_giftcard',
  'hand-raised': 'back_hand',
  'face-smile': 'sentiment_satisfied',
  'musical-note': 'music_note',
  'paint-brush': 'brush',
  scissors: 'content_cut',
  truck: 'local_shipping',
  wifi: 'wifi',
  'building-office-2': 'apartment',
  'building-storefront': 'storefront',
  'squares-2x2': 'grid_view',
  'shopping-bag': 'shopping_bag',
  tag: 'sell',
  clock: 'schedule',
  'clock-solid': 'schedule',
  'academic-cap': 'school',
  'book-open': 'menu_book',
  dumbbell: 'fitness_center',
  'heart-pulse': 'monitor_heart',
  droplet: 'water_drop',
  'water-drop': 'water_drop',
  eye: 'visibility',
  'eye-slash': 'visibility_off',
  'shield-check': 'verified_user',
  'check-circle': 'check_circle',
  information: 'info',
  'information-circle': 'info',
  'arrow-path': 'sync',
  funnel: 'filter_alt',
  'ellipsis-horizontal': 'more_horiz',
  'ellipsis-vertical': 'more_vert',
  'chevron-right': 'chevron_right',
  'chevron-left': 'chevron_left',
  'arrow-left': 'arrow_back',
  'arrow-right': 'arrow_forward',
  plus: 'add',
  'minus-circle': 'remove_circle',
  'x-mark': 'close',
  'x-circle': 'cancel',
  'photo': 'image',
  'document-text': 'description',
  'identification': 'badge',
  'currency-dollar': 'payments',
  banknotes: 'payments',
  'credit-card': 'credit_card',
  phone: 'phone',
  envelope: 'mail',
  'magnifying-glass': 'search',
  'bars-3': 'menu',
  'user-circle': 'account_circle',
  'hand-thumb-up': 'thumb_up',
  'light-bulb': 'lightbulb',
  puzzle: 'extension',
  rocket: 'rocket_launch',
  'cloud': 'cloud',
  'mountain': 'terrain',
  tree: 'park',
  flower: 'local_florist',
  'swatch': 'palette',
  'wrench-screwdriver': 'build',
  cog: 'settings',
  'cog-6-tooth': 'settings',
  'bell': 'notifications',
  'bell-alert': 'notifications_active',
  inbox: 'inbox',
  'archive-box': 'inventory_2',
  trash: 'delete',
  pencil: 'edit',
  'pencil-square': 'edit_square',
  link: 'link',
  'paper-airplane': 'send',
  'chat-bubble-oval-left': 'chat_bubble',
  'microphone': 'mic',
  'video-camera': 'videocam',
  'play': 'play_arrow',
  'pause': 'pause',
  'stop': 'stop',
  'speaker-wave': 'volume_up',
  'adjustments-horizontal': 'tune',
  'funnel-solid': 'filter_alt',
  'self-improvement': 'self_improvement',
  psychology: 'psychology',
  restaurant: 'restaurant',
  'fitness-center': 'fitness_center',
};

const DEFAULT_MATERIAL_ICON = 'spa';

/**
 * Resolve an API Heroicon name (kebab-case) to a Material Symbols ligature.
 */
export function heroiconToMaterialSymbol(
  raw: string | null | undefined,
  fallback: string = DEFAULT_MATERIAL_ICON,
): string {
  if (raw == null || !raw.trim()) {
    return fallback;
  }
  const key = raw.trim().toLowerCase();
  if (HEROICON_TO_MATERIAL[key]) {
    return HEROICON_TO_MATERIAL[key];
  }
  // Already a Material Symbol-style name (snake_case / plain word).
  if (/^[a-z0-9_]+$/.test(key) && !key.includes('-')) {
    return key;
  }
  return fallback;
}
