# Generated by Django 4.2.29 on 2026-03-29 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], default='DRAFT', max_length=20)),
                ('practitioner_alias', models.CharField(blank=True, help_text='Alias for practitioner when user requests specific person', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('special_requests', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='organizations.organization')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('exception_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('MAINTENANCE', 'Maintenance'), ('PRIVATE_EVENT', 'Private Event'), ('WEATHER', 'Weather Related'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_closed', models.BooleanField(default=True)),
                ('alternate_hours', models.JSONField(blank=True, default=dict, help_text='Alternative hours for this date')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='organizations.organization')),
            ],
            options={
                'db_table': 'availability_exceptions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('ROOM', 'Room'), ('EQUIPMENT', 'Equipment'), ('FACILITY', 'Facility')], max_length=15)),
                ('date', models.DateField()),
                ('time_slots', models.JSONField(default=list, help_text='List of available time slots [{"start": "09:00", "end": "10:30"}]')),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('location_details', models.JSONField(blank=True, default=dict, help_text='Location details like room number, floor, etc.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_availability', to='organizations.organization')),
            ],
            options={
                'db_table': 'resource_availability',
                'ordering': ['-date', 'resource_type', 'name'],
                'indexes': [models.Index(fields=['organization'], name='resource_av_organiz_96e3f0_idx'), models.Index(fields=['date'], name='resource_av_date_65bd65_idx'), models.Index(fields=['resource_type'], name='resource_av_resourc_8bf703_idx'), models.Index(fields=['name'], name='resource_av_name_5f4f75_idx')],
                'unique_together': {('organization', 'name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PractitionerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time_slots', models.JSONField(default=list, help_text='List of available time slots [{"start": "09:00", "end": "10:30"}]')),
                ('max_bookings', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('location_type', models.CharField(choices=[('OFFICE', 'At Office/Business Location'), ('HOME', 'At Client Home'), ('VIRTUAL', 'Virtual/Online'), ('MOBILE', 'Mobile Service')], default='OFFICE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practitioner_availability',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user'], name='practitione_user_id_eb9fa0_idx'), models.Index(fields=['date'], name='practitione_date_5f1094_idx'), models.Index(fields=['location_type'], name='practitione_locatio_da4d20_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='organizations.organization')),
            ],
            options={
                'db_table': 'business_hours',
                'ordering': ['day_of_week'],
                'indexes': [models.Index(fields=['organization'], name='business_ho_organiz_6e14f9_idx'), models.Index(fields=['day_of_week'], name='business_ho_day_of__dabd51_idx')],
                'unique_together': {('organization', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='BookingTimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location_type', models.CharField(choices=[('OFFICE', 'At Office/Business Location'), ('HOME', 'At Client Home'), ('VIRTUAL', 'Virtual/Online'), ('MOBILE', 'Mobile Service')], default='OFFICE', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('room_details', models.CharField(blank=True, max_length=255)),
                ('virtual_meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_time_slots',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['booking'], name='booking_tim_booking_a448ee_idx'), models.Index(fields=['start_time'], name='booking_tim_start_t_2cf22e_idx'), models.Index(fields=['end_time'], name='booking_tim_end_tim_f84a62_idx'), models.Index(fields=['location_type'], name='booking_tim_locatio_abe131_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['booking'], name='booking_log_booking_6cb213_idx'), models.Index(fields=['changed_by'], name='booking_log_changed_d1b1b4_idx'), models.Index(fields=['timestamp'], name='booking_log_timesta_fd15ce_idx'), models.Index(fields=['new_status'], name='booking_log_new_sta_496241_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='bookings_user_id_fdc49e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service'], name='bookings_service_876077_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization'], name='bookings_organiz_3fdb19_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['practitioner'], name='bookings_practit_910d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['confirmed_at'], name='bookings_confirm_a63737_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['deleted_at'], name='bookings_deleted_8e622e_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['organization'], name='availabilit_organiz_49408c_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['date'], name='availabilit_date_91e974_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['exception_type'], name='availabilit_excepti_28fbf5_idx'),
        ),
    ]
