# Generated by Django 4.2.29 on 2026-04-04 17:09

from django.db import migrations, models


def _shrink(value, mapping):
    if not value:
        return value
    s = str(value)
    if len(s) <= 1:
        return s
    return mapping.get(s, s)


def forwards_booking_codes(apps, schema_editor):
    AvailabilityException = apps.get_model('bookings', 'AvailabilityException')
    Booking = apps.get_model('bookings', 'Booking')
    BookingLog = apps.get_model('bookings', 'BookingLog')
    BookingTimeSlot = apps.get_model('bookings', 'BookingTimeSlot')
    PractitionerAvailability = apps.get_model('bookings', 'PractitionerAvailability')
    ResourceAvailability = apps.get_model('bookings', 'ResourceAvailability')

    booking_status = {
        'DRAFT': 'D',
        'REQUESTED': 'Q',
        'CONFIRMED': 'F',
        'IN_PROGRESS': 'P',
        'COMPLETED': 'M',
        'CANCELLED': 'X',
        'NO_SHOW': 'N',
        'RESCHEDULED': 'R',
    }
    location = {
        'OFFICE': 'O',
        'HOME': 'H',
        'VIRTUAL': 'V',
        'MOBILE': 'B',
    }
    exc = {
        'HOLIDAY': 'H',
        'MAINTENANCE': 'M',
        'PRIVATE_EVENT': 'P',
        'WEATHER': 'W',
        'OTHER': 'O',
    }
    resource = {
        'ROOM': 'R',
        'EQUIPMENT': 'E',
        'FACILITY': 'F',
    }

    for row in AvailabilityException.objects.all().iterator():
        if row.exception_type and len(str(row.exception_type)) > 1:
            row.exception_type = _shrink(row.exception_type, exc)
            row.save(update_fields=['exception_type'])

    for row in Booking.objects.all().iterator():
        if row.status and len(str(row.status)) > 1:
            row.status = _shrink(row.status, booking_status)
            row.save(update_fields=['status'])

    for row in BookingLog.objects.all().iterator():
        changed = []
        if row.old_status and len(str(row.old_status)) > 1:
            row.old_status = _shrink(row.old_status, booking_status)
            changed.append('old_status')
        if row.new_status and len(str(row.new_status)) > 1:
            row.new_status = _shrink(row.new_status, booking_status)
            changed.append('new_status')
        if changed:
            row.save(update_fields=changed)

    for row in BookingTimeSlot.objects.all().iterator():
        if row.location_type and len(str(row.location_type)) > 1:
            row.location_type = _shrink(row.location_type, location)
            row.save(update_fields=['location_type'])

    for row in PractitionerAvailability.objects.all().iterator():
        if row.location_type and len(str(row.location_type)) > 1:
            row.location_type = _shrink(row.location_type, location)
            row.save(update_fields=['location_type'])

    for row in ResourceAvailability.objects.all().iterator():
        if row.resource_type and len(str(row.resource_type)) > 1:
            row.resource_type = _shrink(row.resource_type, resource)
            row.save(update_fields=['resource_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_booking_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='availabilityexception',
            name='exception_type',
            field=models.CharField(
                choices=[
                    ('H', 'Holiday'),
                    ('M', 'Maintenance'),
                    ('P', 'Private Event'),
                    ('W', 'Weather Related'),
                    ('O', 'Other'),
                ],
                default='O',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(
                choices=[
                    ('D', 'Draft'),
                    ('Q', 'Requested'),
                    ('F', 'Confirmed'),
                    ('P', 'In Progress'),
                    ('M', 'Completed'),
                    ('X', 'Cancelled'),
                    ('N', 'No Show'),
                    ('R', 'Rescheduled'),
                ],
                default='D',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='new_status',
            field=models.CharField(
                choices=[
                    ('D', 'Draft'),
                    ('Q', 'Requested'),
                    ('F', 'Confirmed'),
                    ('P', 'In Progress'),
                    ('M', 'Completed'),
                    ('X', 'Cancelled'),
                    ('N', 'No Show'),
                    ('R', 'Rescheduled'),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='old_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('D', 'Draft'),
                    ('Q', 'Requested'),
                    ('F', 'Confirmed'),
                    ('P', 'In Progress'),
                    ('M', 'Completed'),
                    ('X', 'Cancelled'),
                    ('N', 'No Show'),
                    ('R', 'Rescheduled'),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='bookingtimeslot',
            name='location_type',
            field=models.CharField(
                choices=[
                    ('O', 'At Office/Business Location'),
                    ('H', 'At Client Home'),
                    ('V', 'Virtual/Online'),
                    ('B', 'Mobile Service'),
                ],
                default='O',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='practitioneravailability',
            name='location_type',
            field=models.CharField(
                choices=[
                    ('O', 'At Office/Business Location'),
                    ('H', 'At Client Home'),
                    ('V', 'Virtual/Online'),
                    ('B', 'Mobile Service'),
                ],
                default='O',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='resourceavailability',
            name='resource_type',
            field=models.CharField(
                choices=[('R', 'Room'), ('E', 'Equipment'), ('F', 'Facility')],
                max_length=1,
            ),
        ),
    ]
