# Generated by Django 4.2.29 on 2026-04-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_country_currency_link_and_addresses"),
        ("services", "0005_remove_service_currency_service_accepted_currency_and_more"),
        ("bookings", "0002_alter_availabilityexception_exception_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="currency",
        ),
        migrations.AddField(
            model_name="booking",
            name="accepted_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="organizations.countryacceptedcurrency",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="services.servicevariantmodel",
            ),
        ),
    ]
