# Generated by Django 4.2.29 on 2026-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_currency_booking_accepted_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='share_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='share_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='share_phone',
            field=models.BooleanField(default=False),
        ),
    ]
