# Generated by Django 4.2.29 on 2026-07-18 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_organizationteaminvite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0004_booking_share_email_booking_share_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("C", "Client Request"),
                            ("P", "Practitioner Request"),
                            ("S", "System Automatic"),
                            ("E", "Emergency"),
                            ("T", "Technical Issue"),
                            ("W", "Weather Related"),
                            ("O", "Other"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("reason", models.TextField()),
                ("detailed_explanation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending Review"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                            ("X", "Processed"),
                            ("E", "Escalated"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("processing_notes", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("refund_processed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True, default=list, help_text="List of supporting document URLs or references"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests",
                        to="bookings.booking",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellation_requests_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cancellation_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("S", "Strict Policy"),
                            ("M", "Moderate Policy"),
                            ("F", "Flexible Policy"),
                            ("C", "Custom Policy"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "cancellation_windows",
                    models.JSONField(
                        default=dict, help_text='{"24": 0.1, "48": 0.5, "72": 0.75} - hours before = penalty percentage'
                    ),
                ),
                (
                    "max_cancellation_hours",
                    models.PositiveIntegerField(
                        default=72,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "full_refund_hours",
                    models.PositiveIntegerField(default=48, help_text="Hours before booking for full refund"),
                ),
                (
                    "partial_refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "no_show_policy",
                    models.TextField(default="No refund for no-shows", help_text="Policy for client no-shows"),
                ),
                (
                    "emergency_cancellation",
                    models.BooleanField(default=True, help_text="Allow emergency cancellations with full refund"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_policies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "cancellation_policies",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="CancellationAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("C", "Cancellation Request Created"),
                            ("A", "Cancellation Request Approved"),
                            ("R", "Cancellation Request Rejected"),
                            ("F", "Refund Processed"),
                            ("P", "Cancellation Policy Applied"),
                            ("X", "Automatic Cancellation"),
                            ("M", "Manual Override"),
                        ],
                        max_length=1,
                    ),
                ),
                ("old_data", models.JSONField(blank=True, default=dict, help_text="Snapshot of data before action")),
                ("new_data", models.JSONField(blank=True, default=dict, help_text="Snapshot of data after action")),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_audit_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "cancellation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="bookings.cancellationrequest",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cancellation_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
