# Generated by Django 4.2.29 on 2026-07-18 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_cancellation_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Catalog/service price before platform fee.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform_fee_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform_fee_payer",
            field=models.CharField(blank=True, default="C", help_text="C=client, B=business (snapshot).", max_length=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform_fee_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Snapshot of platform fee percent at booking time.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform_fee_source",
            field=models.CharField(
                blank=True, default="G", help_text="G=global, C=category, O=organization (snapshot).", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount the client owes (base + fee when client pays the platform fee).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
