# Generated by Django 4.2.29 on 2026-07-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_platform_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="platform_fee_payer",
            field=models.CharField(
                choices=[("C", "Client"), ("B", "Business")],
                default="C",
                help_text="Who pays the platform fee (snapshot at booking time).",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="platform_fee_source",
            field=models.CharField(
                choices=[("G", "Global"), ("C", "Category"), ("O", "Organization")],
                default="G",
                help_text="Where the fee rate was resolved from (snapshot).",
                max_length=1,
            ),
        ),
    ]
