# Generated by Django 4.2.29 on 2026-07-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0007_platform_fee_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRescheduleProposal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("proposed_by", models.CharField(choices=[("C", "Client"), ("B", "Business")], max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("A", "Accepted"), ("D", "Declined")], default="P", max_length=1
                    ),
                ),
                (
                    "time_slots",
                    models.JSONField(
                        default=list,
                        help_text="Proposed slots as list of dicts (start_time, end_time, location_type, …).",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_proposals",
                        to="bookings.booking",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reschedule_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reschedule_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_reschedule_proposals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["booking"], name="booking_res_booking_00f63d_idx"),
                    models.Index(fields=["status"], name="booking_res_status_3b4467_idx"),
                ],
            },
        ),
    ]
