# Generated by Django 4.2.29 on 2026-07-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_audit_event_mixin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0008_accepted_venues_reschedule_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cancellationauditlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="cancellationauditlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="cancellationauditlog",
            name="audit_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.auditevent",
            ),
        ),
        migrations.CreateModel(
            name="BookingActionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("old_data", models.JSONField(blank=True, default=dict)),
                ("new_data", models.JSONField(blank=True, default=dict)),
                (
                    "audit_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.auditevent",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="action_logs", to="bookings.booking"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_action_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["booking", "created_at"], name="booking_act_booking_b3eba5_idx"),
                    models.Index(fields=["action"], name="booking_act_action_25f8f5_idx"),
                ],
            },
        ),
    ]
