# Generated by Django 4.2.29 on 2026-07-26 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_audit_event_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="inscription_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="One-time verification fee included in client charge when due (snapshot).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
