# Generated by Django 4.2.29 on 2026-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_payment_team_notification_kinds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("booking_received", "Booking received"),
                    ("booking_confirmed", "Booking confirmed"),
                    ("reschedule_proposed", "Reschedule proposed"),
                    ("reschedule_accepted", "Reschedule accepted"),
                    ("reschedule_declined", "Reschedule declined"),
                    ("booking_cancelled", "Booking cancelled"),
                    ("payment_received", "Payment received"),
                    ("wallet_topped_up", "Wallet topped up"),
                    ("team_invite", "Team invite"),
                    ("message_invite", "Message invite"),
                    ("message_received", "Message received"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
