# Generated by Django 4.2.29 on 2026-07-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notification_audience"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_8f5da5_idx",
            old_name="notificatio_user_id_aud_idx",
        ),
    ]
